; NOTE: Assertions have been autogenerated by utils/update_analyze_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes='print<scalar-evolution>' -disable-output < %s 2>&1 | FileCheck %s

; The flags of an increment reach the pre-inc add recurrence of its phi only
; where the phi being poison, or the increment being poison on a backedge that
; is taken, is undefined behavior. Otherwise the flag would be a claim about
; every value that shares the expression.
; https://github.com/llvm/llvm-project/issues/175729

declare i1 @cond(i16)
declare void @use(i16 noundef)

; %nextnext is poison on the iteration before the last and nothing observes
; it: {-3,+,1} is 0 on the last iteration, and is not <nuw>.
define i1 @unobserved() {
; CHECK-LABEL: 'unobserved'
; CHECK-NEXT:  Classifying expressions for: @unobserved
; CHECK-NEXT:    %next = phi i16 [ -3, %entry ], [ %nextnext, %latch ]
; CHECK-NEXT:    --> {-3,+,1}<nsw><%header> U: [-3,1) S: [-3,1) Exits: <<Unknown>> LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %iter = phi i16 [ -4, %entry ], [ %next, %latch ]
; CHECK-NEXT:    --> {-4,+,1}<nsw><%header> U: [-4,0) S: [-4,0) Exits: <<Unknown>> LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %nextnext = add nuw i16 %next, 1
; CHECK-NEXT:    --> {-2,+,1}<nsw><%header> U: [-2,2) S: [-2,2) Exits: <<Unknown>> LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %c = call i1 @cond(i16 %iter)
; CHECK-NEXT:    --> %c U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Variant }
; CHECK-NEXT:    %r = phi i1 [ true, %header ], [ false, %latch ]
; CHECK-NEXT:    --> %done U: full-set S: full-set
; CHECK-NEXT:  Determining loop execution counts for: @unobserved
; CHECK-NEXT:  Loop %header: <multiple exits> Unpredictable backedge-taken count.
; CHECK-NEXT:    exit count for header: i16 3
; CHECK-NEXT:    exit count for latch: ***COULDNOTCOMPUTE***
; CHECK-NEXT:  Loop %header: constant max backedge-taken count is i16 3
; CHECK-NEXT:  Loop %header: symbolic max backedge-taken count is i16 3
; CHECK-NEXT:    symbolic max exit count for header: i16 3
; CHECK-NEXT:    symbolic max exit count for latch: ***COULDNOTCOMPUTE***
;
entry:
  br label %header

header:
  %next = phi i16 [ -3, %entry ], [ %nextnext, %latch ]
  %iter = phi i16 [ -4, %entry ], [ %next, %latch ]
  %done = icmp eq i16 %iter, -1
  br i1 %done, label %exit, label %latch

latch:
  %nextnext = add nuw i16 %next, 1
  %c = call i1 @cond(i16 %iter)
  br i1 %c, label %exit, label %header

exit:
  %r = phi i1 [ true, %header ], [ false, %latch ]
  ret i1 %r
}

; The header passes %next where poison is undefined behavior, so the increment
; did not wrap on any backedge that was taken.
define i1 @phi_observed(i16 %start) {
; CHECK-LABEL: 'phi_observed'
; CHECK-NEXT:  Classifying expressions for: @phi_observed
; CHECK-NEXT:    %next = phi i16 [ %start, %entry ], [ %nextnext, %latch ]
; CHECK-NEXT:    --> {%start,+,1}<nuw><%header> U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %c = call i1 @cond(i16 0)
; CHECK-NEXT:    --> %c U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Variant }
; CHECK-NEXT:    %nextnext = add nuw i16 %next, 1
; CHECK-NEXT:    --> {(1 + %start),+,1}<nw><%header> U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Computable }
; CHECK-NEXT:  Determining loop execution counts for: @phi_observed
; CHECK-NEXT:  Loop %header: Unpredictable backedge-taken count.
; CHECK-NEXT:  Loop %header: Unpredictable constant max backedge-taken count.
; CHECK-NEXT:  Loop %header: Unpredictable symbolic max backedge-taken count.
;
entry:
  br label %header

header:
  %next = phi i16 [ %start, %entry ], [ %nextnext, %latch ]
  call void @use(i16 noundef %next)
  %c = call i1 @cond(i16 0)
  br i1 %c, label %exit, label %latch

latch:
  %nextnext = add nuw i16 %next, 1
  br label %header

exit:
  ret i1 true
}

; A block that dominates the latch passes %nextnext where poison is undefined
; behavior, so it is not poison on any backedge that is taken.
define i1 @increment_observed(i16 %start) {
; CHECK-LABEL: 'increment_observed'
; CHECK-NEXT:  Classifying expressions for: @increment_observed
; CHECK-NEXT:    %next = phi i16 [ %start, %entry ], [ %nextnext, %latch ]
; CHECK-NEXT:    --> {%start,+,1}<nuw><%header> U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %c = call i1 @cond(i16 0)
; CHECK-NEXT:    --> %c U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Variant }
; CHECK-NEXT:    %nextnext = add nuw i16 %next, 1
; CHECK-NEXT:    --> {(1 + %start),+,1}<nw><%header> U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Computable }
; CHECK-NEXT:  Determining loop execution counts for: @increment_observed
; CHECK-NEXT:  Loop %header: Unpredictable backedge-taken count.
; CHECK-NEXT:  Loop %header: Unpredictable constant max backedge-taken count.
; CHECK-NEXT:  Loop %header: Unpredictable symbolic max backedge-taken count.
;
entry:
  br label %header

header:
  %next = phi i16 [ %start, %entry ], [ %nextnext, %latch ]
  %c = call i1 @cond(i16 0)
  br i1 %c, label %exit, label %latch

latch:
  %nextnext = add nuw i16 %next, 1
  call void @use(i16 noundef %nextnext)
  br label %header

exit:
  ret i1 true
}

; The use of %nextnext does not dominate the latch: a backedge can be taken
; with %nextnext poison.
define i1 @increment_observed_on_one_path(i16 %start) {
; CHECK-LABEL: 'increment_observed_on_one_path'
; CHECK-NEXT:  Classifying expressions for: @increment_observed_on_one_path
; CHECK-NEXT:    %next = phi i16 [ %start, %entry ], [ %nextnext, %latch ]
; CHECK-NEXT:    --> {%start,+,1}<%header> U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %c = call i1 @cond(i16 0)
; CHECK-NEXT:    --> %c U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Variant }
; CHECK-NEXT:    %nextnext = add nuw i16 %next, 1
; CHECK-NEXT:    --> {(1 + %start),+,1}<%header> U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Computable }
; CHECK-NEXT:    %c2 = call i1 @cond(i16 1)
; CHECK-NEXT:    --> %c2 U: full-set S: full-set Exits: <<Unknown>> LoopDispositions: { %header: Variant }
; CHECK-NEXT:  Determining loop execution counts for: @increment_observed_on_one_path
; CHECK-NEXT:  Loop %header: Unpredictable backedge-taken count.
; CHECK-NEXT:  Loop %header: Unpredictable constant max backedge-taken count.
; CHECK-NEXT:  Loop %header: Unpredictable symbolic max backedge-taken count.
;
entry:
  br label %header

header:
  %next = phi i16 [ %start, %entry ], [ %nextnext, %latch ]
  %c = call i1 @cond(i16 0)
  br i1 %c, label %exit, label %body

body:
  %nextnext = add nuw i16 %next, 1
  %c2 = call i1 @cond(i16 1)
  br i1 %c2, label %observe, label %latch

observe:
  call void @use(i16 noundef %nextnext)
  br label %latch

latch:
  br label %header

exit:
  ret i1 true
}
