; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=indvars -S < %s | FileCheck %s

; The nuw on %nextnext makes it poison on the iteration before the last, and
; nothing observes that poison: the loop leaves through %done first. %next's
; add recurrence must not take the flag, or %iter + 1, a defined value that is
; the same SCEV expression, becomes "never zero" and the only exit %iter == -1
; takes folds to false.
; https://github.com/llvm/llvm-project/issues/175729

declare i1 @cond.i8(i8)
declare i1 @cond.i16(i16)
declare i1 @cond.i32(i32)
declare i1 @cond.i64(i64)
declare i1 @cond.i128(i128)

; The start is constant and %done is the loop's only exit.
define i1 @only_exit() {
; CHECK-LABEL: define i1 @only_exit() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    br i1 true, label %[[EXIT:.*]], label %[[LATCH:.*]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    br label %[[HEADER]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i1 true
;
entry:
  br label %header

header:
  %next = phi i16 [ -3, %entry ], [ %nextnext, %latch ]
  %iter = phi i16 [ -4, %entry ], [ %next, %latch ]
  %done = icmp eq i16 %iter, -1
  br i1 %done, label %exit, label %latch

latch:
  %nextnext = add nuw i16 %next, 1
  br label %header

exit:
  ret i1 true
}

; A second exit the analysis cannot see through.
define i1 @second_exit() {
; CHECK-LABEL: define i1 @second_exit() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[NEXT:%.*]] = phi i16 [ -3, %[[ENTRY]] ], [ [[NEXTNEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[ITER:%.*]] = phi i16 [ -4, %[[ENTRY]] ], [ [[NEXT]], %[[LATCH]] ]
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i16 [[ITER]], -1
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[NEXTNEXT]] = add nuw nsw i16 [[NEXT]], 1
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond.i16(i16 [[ITER]])
; CHECK-NEXT:    br i1 [[C]], label %[[EXIT]], label %[[HEADER]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[R:%.*]] = phi i1 [ true, %[[HEADER]] ], [ false, %[[LATCH]] ]
; CHECK-NEXT:    ret i1 [[R]]
;
entry:
  br label %header

header:
  %next = phi i16 [ -3, %entry ], [ %nextnext, %latch ]
  %iter = phi i16 [ -4, %entry ], [ %next, %latch ]
  %done = icmp eq i16 %iter, -1
  br i1 %done, label %exit, label %latch

latch:
  %nextnext = add nuw i16 %next, 1
  %c = call i1 @cond.i16(i16 %iter)
  br i1 %c, label %exit, label %header

exit:
  %r = phi i1 [ true, %header ], [ false, %latch ]
  ret i1 %r
}

; The start is not constant, only bounded.
define i1 @ranged_start(i16 range(i16 10, 100) %start) {
; CHECK-LABEL: define i1 @ranged_start(
; CHECK-SAME: i16 range(i16 10, 100) [[START:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[S1:%.*]] = add i16 [[START]], 1
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[NEXT:%.*]] = phi i16 [ [[S1]], %[[ENTRY]] ], [ [[NEXTNEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[ITER:%.*]] = phi i16 [ [[START]], %[[ENTRY]] ], [ [[NEXT]], %[[LATCH]] ]
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i16 [[ITER]], -1
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[NEXTNEXT]] = add nuw i16 [[NEXT]], 1
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond.i16(i16 [[ITER]])
; CHECK-NEXT:    br i1 [[C]], label %[[EXIT]], label %[[HEADER]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[R:%.*]] = phi i1 [ true, %[[HEADER]] ], [ false, %[[LATCH]] ]
; CHECK-NEXT:    ret i1 [[R]]
;
entry:
  %s1 = add i16 %start, 1
  br label %header

header:
  %next = phi i16 [ %s1, %entry ], [ %nextnext, %latch ]
  %iter = phi i16 [ %start, %entry ], [ %next, %latch ]
  %done = icmp eq i16 %iter, -1
  br i1 %done, label %exit, label %latch

latch:
  %nextnext = add nuw i16 %next, 1
  %c = call i1 @cond.i16(i16 %iter)
  br i1 %c, label %exit, label %header

exit:
  %r = phi i1 [ true, %header ], [ false, %latch ]
  ret i1 %r
}

; The same at i8: no width is exempt.
define i1 @second_exit_i8() {
; CHECK-LABEL: define i1 @second_exit_i8() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[NEXT:%.*]] = phi i8 [ -3, %[[ENTRY]] ], [ [[NEXTNEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[ITER:%.*]] = phi i8 [ -4, %[[ENTRY]] ], [ [[NEXT]], %[[LATCH]] ]
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i8 [[ITER]], -1
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[NEXTNEXT]] = add nuw nsw i8 [[NEXT]], 1
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond.i8(i8 [[ITER]])
; CHECK-NEXT:    br i1 [[C]], label %[[EXIT]], label %[[HEADER]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[R:%.*]] = phi i1 [ true, %[[HEADER]] ], [ false, %[[LATCH]] ]
; CHECK-NEXT:    ret i1 [[R]]
;
entry:
  br label %header

header:
  %next = phi i8 [ -3, %entry ], [ %nextnext, %latch ]
  %iter = phi i8 [ -4, %entry ], [ %next, %latch ]
  %done = icmp eq i8 %iter, -1
  br i1 %done, label %exit, label %latch

latch:
  %nextnext = add nuw i8 %next, 1
  %c = call i1 @cond.i8(i8 %iter)
  br i1 %c, label %exit, label %header

exit:
  %r = phi i1 [ true, %header ], [ false, %latch ]
  ret i1 %r
}

; The same at i32: no width is exempt.
define i1 @second_exit_i32() {
; CHECK-LABEL: define i1 @second_exit_i32() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[NEXT:%.*]] = phi i32 [ -3, %[[ENTRY]] ], [ [[NEXTNEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[ITER:%.*]] = phi i32 [ -4, %[[ENTRY]] ], [ [[NEXT]], %[[LATCH]] ]
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i32 [[ITER]], -1
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[NEXTNEXT]] = add nuw nsw i32 [[NEXT]], 1
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond.i32(i32 [[ITER]])
; CHECK-NEXT:    br i1 [[C]], label %[[EXIT]], label %[[HEADER]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[R:%.*]] = phi i1 [ true, %[[HEADER]] ], [ false, %[[LATCH]] ]
; CHECK-NEXT:    ret i1 [[R]]
;
entry:
  br label %header

header:
  %next = phi i32 [ -3, %entry ], [ %nextnext, %latch ]
  %iter = phi i32 [ -4, %entry ], [ %next, %latch ]
  %done = icmp eq i32 %iter, -1
  br i1 %done, label %exit, label %latch

latch:
  %nextnext = add nuw i32 %next, 1
  %c = call i1 @cond.i32(i32 %iter)
  br i1 %c, label %exit, label %header

exit:
  %r = phi i1 [ true, %header ], [ false, %latch ]
  ret i1 %r
}

; The same at i64: no width is exempt.
define i1 @second_exit_i64() {
; CHECK-LABEL: define i1 @second_exit_i64() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[NEXT:%.*]] = phi i64 [ -3, %[[ENTRY]] ], [ [[NEXTNEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[ITER:%.*]] = phi i64 [ -4, %[[ENTRY]] ], [ [[NEXT]], %[[LATCH]] ]
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i64 [[ITER]], -1
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[NEXTNEXT]] = add nuw nsw i64 [[NEXT]], 1
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond.i64(i64 [[ITER]])
; CHECK-NEXT:    br i1 [[C]], label %[[EXIT]], label %[[HEADER]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[R:%.*]] = phi i1 [ true, %[[HEADER]] ], [ false, %[[LATCH]] ]
; CHECK-NEXT:    ret i1 [[R]]
;
entry:
  br label %header

header:
  %next = phi i64 [ -3, %entry ], [ %nextnext, %latch ]
  %iter = phi i64 [ -4, %entry ], [ %next, %latch ]
  %done = icmp eq i64 %iter, -1
  br i1 %done, label %exit, label %latch

latch:
  %nextnext = add nuw i64 %next, 1
  %c = call i1 @cond.i64(i64 %iter)
  br i1 %c, label %exit, label %header

exit:
  %r = phi i1 [ true, %header ], [ false, %latch ]
  ret i1 %r
}

; The same at i128: no width is exempt.
define i1 @second_exit_i128() {
; CHECK-LABEL: define i1 @second_exit_i128() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[NEXT:%.*]] = phi i128 [ -3, %[[ENTRY]] ], [ [[NEXTNEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[ITER:%.*]] = phi i128 [ -4, %[[ENTRY]] ], [ [[NEXT]], %[[LATCH]] ]
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i128 [[ITER]], -1
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT:.*]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[NEXTNEXT]] = add nuw nsw i128 [[NEXT]], 1
; CHECK-NEXT:    [[C:%.*]] = call i1 @cond.i128(i128 [[ITER]])
; CHECK-NEXT:    br i1 [[C]], label %[[EXIT]], label %[[HEADER]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[R:%.*]] = phi i1 [ true, %[[HEADER]] ], [ false, %[[LATCH]] ]
; CHECK-NEXT:    ret i1 [[R]]
;
entry:
  br label %header

header:
  %next = phi i128 [ -3, %entry ], [ %nextnext, %latch ]
  %iter = phi i128 [ -4, %entry ], [ %next, %latch ]
  %done = icmp eq i128 %iter, -1
  br i1 %done, label %exit, label %latch

latch:
  %nextnext = add nuw i128 %next, 1
  %c = call i1 @cond.i128(i128 %iter)
  br i1 %c, label %exit, label %header

exit:
  %r = phi i1 [ true, %header ], [ false, %latch ]
  ret i1 %r
}

; The loop rustc's RangeInclusive<u16> made of `for port in 0xFFFC..=0xFFFF`,
; where the miscompile was found.
define i1 @probe() {
; CHECK-LABEL: define i1 @probe() {
; CHECK-NEXT:  [[START:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[NEXT:%.*]] = phi i16 [ -3, %[[START]] ], [ [[NEXTNEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[ITER:%.*]] = phi i16 [ -4, %[[START]] ], [ [[NEXT]], %[[LATCH]] ]
; CHECK-NEXT:    switch i16 [[ITER]], label %[[MASK:.*]] [
; CHECK-NEXT:      i16 161, label %[[EXIT:.*]]
; CHECK-NEXT:      i16 160, label %[[EXIT]]
; CHECK-NEXT:      i16 113, label %[[EXIT]]
; CHECK-NEXT:      i16 112, label %[[EXIT]]
; CHECK-NEXT:      i16 33, label %[[EXIT]]
; CHECK-NEXT:      i16 32, label %[[EXIT]]
; CHECK-NEXT:      i16 3320, label %[[EXIT]]
; CHECK-NEXT:      i16 3321, label %[[EXIT]]
; CHECK-NEXT:      i16 178, label %[[LATCH]]
; CHECK-NEXT:    ]
; CHECK:       [[MASK]]:
; CHECK-NEXT:    [[M:%.*]] = and i16 [[ITER]], -4
; CHECK-NEXT:    [[C1:%.*]] = icmp eq i16 [[M]], 3324
; CHECK-NEXT:    br i1 [[C1]], label %[[EXIT]], label %[[LAST:.*]]
; CHECK:       [[LAST]]:
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i16 [[ITER]], -1
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[NEXTNEXT]] = add nuw i16 [[NEXT]], 1
; CHECK-NEXT:    [[M2:%.*]] = and i16 [[NEXT]], -8
; CHECK-NEXT:    [[C2:%.*]] = icmp eq i16 [[M2]], 1016
; CHECK-NEXT:    br i1 [[C2]], label %[[EXIT]], label %[[HEADER]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[R:%.*]] = phi i1 [ false, %[[MASK]] ], [ false, %[[HEADER]] ], [ false, %[[HEADER]] ], [ false, %[[LATCH]] ], [ false, %[[HEADER]] ], [ false, %[[HEADER]] ], [ false, %[[HEADER]] ], [ false, %[[HEADER]] ], [ false, %[[HEADER]] ], [ false, %[[HEADER]] ], [ true, %[[LAST]] ]
; CHECK-NEXT:    ret i1 [[R]]
;
start:
  br label %header

header:
  %next = phi i16 [ -3, %start ], [ %nextnext, %latch ]
  %iter = phi i16 [ -4, %start ], [ %next, %latch ]
  switch i16 %iter, label %mask [
  i16 161, label %exit
  i16 160, label %exit
  i16 113, label %exit
  i16 112, label %exit
  i16 33, label %exit
  i16 32, label %exit
  i16 3320, label %exit
  i16 3321, label %exit
  i16 178, label %latch
  ]

mask:
  %m = and i16 %iter, -4
  %c1 = icmp eq i16 %m, 3324
  br i1 %c1, label %exit, label %last

last:
  %done = icmp eq i16 %iter, -1
  br i1 %done, label %exit, label %latch

latch:
  %nextnext = add nuw i16 %next, 1
  %m2 = and i16 %next, -8
  %c2 = icmp eq i16 %m2, 1016
  br i1 %c2, label %exit, label %header

exit:
  %r = phi i1 [ false, %mask ], [ false, %header ], [ false, %header ], [ false, %latch ], [ false, %header ], [ false, %header ], [ false, %header ], [ false, %header ], [ false, %header ], [ false, %header ], [ true, %last ]
  ret i1 %r
}
